name: Ansible CI

on:
  push:
    branches:
      - main
    paths:
      - "*.yml"
      - "monitoring_config/**"
      - "apps_config/**"
      - "system_config/**"
      - ".github/workflows/**"
  pull_request:
    branches:
      - main
    paths:
      - "*.yml"
      - "monitoring_config/**"
      - "apps_config/**"
      - "system_config/**"
      - ".github/workflows/**"

jobs:
  ansible-ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Ansible
        run: |
          python -m pip install --upgrade pip
          pip install ansible ansible-lint

      - name: Run Ansible Lint
        run: ansible-lint

      - name: Run Ansible syntax check
        run: ansible-playbook -i hosts site.yml --syntax-check
