name: Ansible Lint
on:
  push:
    branches:
      - main
    paths:
      - "*.yml"
      - "monitoring_config/**"
      - "apps_config/**"
      - "system_config/**"
  pull_request:
    branches:
      - main
    paths:
      - "*.yml"
      - "monitoring_config/**"
      - "apps_config/**"
      - "system_config/**"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Run Ansible Lint
        uses: ansible/ansible-lint@main
